CLI overview: fix CSV examples
The `-c` arg was missing from the example commands, leading to errors:

    $ cat test.csv | duckdb "SELECT * FROM read_csv('/dev/stdin')"
    Error: unable to open database "SELECT * FROM read_csv('/dev/stdin')":
    IO Error: Cannot open file "SELECT * FROM read_csv('/dev/stdin')": No such file or directory

Note: this also applies to `docs/archive/1.0/api/cli/overview.md` which was
left unmodified per CONTRIBUTING.md.